apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-x1wj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-x1wj@sha256:9db13e02bccf52470540883d582d3a630c82e0870fa593b397ab4c94d68be0dd
        name: my-nodejs
        resources: {}
status: {}
